### ISSUE TITLE
Markdown issues w/ WebRTC_PrivacyNotice links

### ISSUE THREAD

**Issue by pdehaan** [mozilla/legal-docs#336]
In [/WebRTC_PrivacyNotice/en-US.md](https://github.com/mozilla/legal-docs/blob/master/WebRTC_PrivacyNotice/en-US.md) (and presumably other locales) it looks like we have some invalid markdown. Note the space in the link below (betweenst `[here]` and `(https://...)`):

``` md
 click [here] (https://www.mozilla.org/en-US/privacy/firefox-cloud/).
```

Some markdown processors may be smart enough to correct that for you (GitHub.com seems to be pretty clever), but other parsers such as npm's **marked** and whatever we're using on https://www.mozilla.org/en-US/privacy/firefox-hello/ isn't so clever (note the following unparsed output):

``` html
To learn more about how data is used by Firefox Accounts, click [here] (https://www.mozilla.org/en-US/privacy/firefox-cloud/).
```

**Comment by kyoshino** [comment]
This has been fixed in #368.

**Comment by MikkCZ** [comment]
I still see this invalid markdown `] (` in the following files:
```Firefox-Addons-Distribution-Agreement-20150522
firefox_os_privacy_notice/da.md
firefox_os_privacy_notice/lt-LV.md
firefox_os_privacy_notice/sl.md
firefox_privacy_notice/bn-BD.md
firefox_privacy_notice/bn-IN.md
marketplace_developer_agreement/ar.md
marketplace_developer_agreement/bn-BD.md
marketplace_developer_agreement/bn-IN.md
marketplace_developer_agreement/el.md
marketplace_developer_agreement/es-ES.md
marketplace_developer_agreement/fr.md
marketplace_developer_agreement/hi.md
marketplace_developer_agreement/hr.md
marketplace_developer_agreement/sw.md
marketplace_developer_agreement/ta.md
mozilla_privacy_policy/pl.md
websites_privacy_notice/ar.md```
